import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavbarWrapper from "@/components/NavbarWrapper";
import Toast from "@/components/Toast";
import { UserProvider } from "@/context/UserContext";
import { ModalProvider } from "@/components/ui/animated-modal";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DevAcademy",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <ModalProvider>
            <NavbarWrapper />
            {children}
            <Toast />
          </ModalProvider>
        </UserProvider>
      </body>
    </html>
  );
}
